# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  upload:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: TwitterFanOutConsumer-Jar
          path: target/TwitterFanOutConsumer-makeittotop-0.1-jar-with-dependencies.jar
          retention-days: 7
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  download:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: TwitterFanOutConsumer-Jar
          path: ~/Downloads

      - name: Display structure of downloaded files
        run: ls -lth
        working-directory: ~/Downloads



